### ISSUE TITLE
Fix typo in example for first assignment

### ISSUE THREAD

**Issue by BeneHTWG** [pkeilbach/htwg-practical-nlp#168]
- in `python_basics.py` for the `print_product_price()` function the given [output example](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/src/htwgnlp/python_basics.py#L131) is: 'The price of **a** \<product\> is \<price\> USD.'
- However the [expected behaviour](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/tests/htwgnlp/test_python_basics.py#L116-L120) in the unittest is 'The price of \<product\> is \<price\> USD.', so the 'a' is missing
- **proposal:** just add the 'a' in the test

**Comment by BeneHTWG** [comment]
@pkeilbach, I would like to work on the issue but I don't have access to assign myself currently.

**Comment by pkeilbach** [comment]
> @pkeilbach, I would like to work on the issue but I don't have access to assign myself currently.

Thanks for the heads up, I just assigned you 👍🏼
