### ISSUE TITLE
Bug/typo getting_started.md (make mkdocs)

### ISSUE THREAD

**Issue by TobiTgl** [pkeilbach/htwg-practical-nlp#172]
I found a bug/typo in [getting_started.md](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/docs/getting_started.md)
In line 157 it says to use `make docs` to run lecture notes locally however this does not work and instead should be:
`make mkdocs`

**Comment by pkeilbach** [comment]
Thanks for reporting, @TobiTgl !

This was already fixed by #169 (specifically https://github.com/pkeilbach/htwg-practical-nlp/pull/169/commits/94e1669bcfee324a25fbe4f80451ea79d74faf6b)
