### ISSUE TITLE
Add autoreload functionality to Jupyter Notebooks

### ISSUE THREAD

**Issue by KrasserKai** [pkeilbach/htwg-practical-nlp#189]
When you make changes to a Python module that you import into a Jupyter notebook, it's necessary to restart the kernel for the changes to appear. This can be very tedious when you're actively developing the module while testing it in the notebook.

To fix this problem, Jupyter provides a simple functionality called **"autoreload"**, which automatically reloads modules so that changes appear directly. 

You just need to include the following lines in a code cell at the top of the notebook:

```python
%load_ext autoreload
%autoreload 2
```
This reloads the modules each time python code is executed, so when you make a change to the module and execute it in Jupyter the changes appear immediatly without having to restart the kernel.

**Comment by pkeilbach** [comment]
fixed by #190
