### ISSUE TITLE
Add pre-commit hook to strip Jupyter Notebook outputs

### ISSUE THREAD

**Issue by KrasserKai** [pkeilbach/htwg-practical-nlp#191]
Currently, the outputs of Jupyter Notebooks are not stripped before committing to Git. This can lead to unnecessary changes in the repository, as the output cells often contain metadata about the environment (e.g., execution count, Python version, kernel details) that generated the output.

These metadata changes make it challenging for multiple collaborators to work on the same notebooks, as simply executing a cell updates the metadata, which Git treats as file changes. This can clutter the Git history with irrelevant changes and lead to frequent merge conflicts.

A proposed change would be implementing a pre-commit hook that strips the Jupyter output. This ensures that only the actual notebooks, without any generated output, will be pushed to Git. This would also mean that somebody executing the notebook doesn't get "spoiled" by the already available output the first time they execute the notebook.

**Comment by pkeilbach** [comment]
This is a very good idea, @KrasserKai !

Give me a thumbs up if you want to work on this! My current estimation would be 2 bonus points! 😉

**Comment by TobiTgl** [comment]
Kai already has his 5 Bonus point so if its okay I would work on it. Me and Kai already talked about this.

**Comment by pkeilbach** [comment]
closed by #206
