### ISSUE TITLE
Increase tolerance for test_cosine_similarity in assignment 4

### ISSUE THREAD

**Issue by KrasserKai** [pkeilbach/htwg-practical-nlp#192]
In Assignment 4, one of the tasks is to implement cosine similarity between a word and the embeddings. I correctly implemented the method but had problems passing the test (**test_cosine_similarity**) due to small numerical issues, likely because the tolerance in the test is too small.

In one example, I got `-0.03731010385073611` instead of the expected `-0.037310105006509546` (absolute difference: `3.28e-08`, relative difference: `2.58e-07`). This error is so small that I am certain it is due to numerical issues.

That's why I think it is necessary to increase the tolerance in the test slightly.

**Comment by pkeilbach** [comment]
fixed by #193
