### ISSUE TITLE
Add a index slicing exercise to Python basics assignment

### ISSUE THREAD

**Issue by pkeilbach** [pkeilbach/htwg-practical-nlp#207]
Index slicing is very common in Python, and it should be added to [assignment-0](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/src/htwgnlp/python_basics.py).

Acceptance criteria:
- add a function to [assignment 0](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/src/htwgnlp/python_basics.py) where students need to implement [Python index slicing](https://realpython.com/lessons/indexing-and-slicing/)
- add test cases for that new function to [test_python_basics.py](https://github.com/pkeilbach/htwg-practical-nlp/blob/main/tests/htwgnlp/test_python_basics.py)

**Comment by SponsoredByPuma** [comment]
I would work on this issue :)
