### ISSUE TITLE
Presentation topic pool winter term 2024/25

### ISSUE THREAD

**Issue by pkeilbach** [pkeilbach/htwg-practical-nlp#90]
Here are some topic suggestions for the presentations.

Please comment the topic you want to work on!

## Tools and Frameworks

- GitHub Copilot
- Langchain 👉🏼 @Alex-J-W 
- Grammarly 👉🏼 @Leamayf 
- Scikit learn for NLP 👉🏼 @TobiTgl 
- PyTorch for NLP 👉🏼 @KrasserKai 
- Tensorflow for NLP

## Misc

- Open Source LLMs 👉🏼 @TimSchober 
- AI Made in Germany and the EU 👉🏼 @SponsoredByPuma 
- Elasticsearch and Information Retrieval 👉🏼 @khadidja-kebaili 
- Visualizing Text Data
- Data Storytelling 👉🏼 @mayah1010 
- Retrieval augmented generation (RAG) 👉🏼 @ari21itwm 
- Hallucination 👉🏼 @lauraschrwr 
- Text-to-Speech and Speech-to-Text
- Implementing a ReAct agent with langchain
- Multi-modal models

## Papers / Theoretical concepts

- [Byte pair encoding](https://web.archive.org/web/20160326130908/http://www.csse.monash.edu.au/cluster/RJK/Compress/problem.html) algorithm and the tiktoken library
- [LongCite: Enabling LLMs to Generate Fine-grained Citations in Long-context QA](https://arxiv.org/abs/2409.02897)
- [Automating Enterprise Data Engineering with LLMs](https://openreview.net/forum?id=m85fYEJtDc#discussion)
- [To CoT or Not to CoT? Chain of Thought helps mainly on Math and Symbolic Reasoning](https://arxiv.org/pdf/2409.12183v1) 👉🏼 @BeneHTWG 
- [GSM-Symbolic: Understanding the Limitations of Mathematical Reasoning in Large Language Models](https://arxiv.org/pdf/2410.05229)
- [A Peek into TokenBias: Large Language Models Are Not Yet Genuine Reasoners](https://arxiv.org/pdf/2406.11050)
- [Thinking LLMs: General Instruction Following with Thought Generation](https://arxiv.org/pdf/2410.10630) 👉🏼 @LilianCharlotte 
- [Improving pretraining data using perplexity correlations](https://arxiv.org/pdf/2409.05816v1)
- [Addition is all you need for energy-efficient language models](https://arxiv.org/pdf/2410.00907)
- [Emergent Abilities of Large Language Models](https://arxiv.org/abs/2206.07682)
- [Training Language Models to Follow Instructions with Human Feedback](https://arxiv.org/abs/2203.02155)
- [Language Models as Zero-Shot Planners](https://arxiv.org/abs/2205.11916)
- [Self-Supervised Policy Adaptation during Deployment](https://arxiv.org/abs/2007.04309)
- [Compact Language Models via Pruning and Knowledge Distillation](https://arxiv.org/abs/2407.14679)
- [From Single to Multi: How LLMs Hallucinate in Multi-Document Summarization](https://arxiv.org/pdf/2410.13961)
- [A comprehensive survey of Small Language Models: Techniques, Applications, Collaboration with LLMs and Trustworthiness](https://arxiv.org/pdf/2411.03350)
- [What Matters in Transformers? Not All Attention is Needed](https://arxiv.org/abs/2406.15786)
- [ReAct: Synergizing Reasoning and Acting in Language Models](https://arxiv.org/abs/2210.03629)

**Comment by KrasserKai** [comment]
Ich würde gerne das Thema "PyTorch for NLP" machen.

**Comment by tiffanyblum** [comment]
Ich würde gerne das Thema "Tensorflow for NLP" machen

**Comment by BeneHTWG** [comment]
Ich würde gerne das Thema "Chain of Thought" machen

**Comment by ari21itwm** [comment]
ich würde gerne Retrieval augmented generation (RAG) machen

**Comment by lauraschrwr** [comment]
Ich würde gerne das Thema "Hallucination"

**Comment by TobiTgl** [comment]
Ich würde mir gerne scikit learn präsentieren

**Comment by SponsoredByPuma** [comment]
ich würde das Thema AI Made in Germany and the EU nehmen

**Comment by khadidja-kebaili** [comment]
Ich würde dann gerne das Thema Elasticsearch and Information Retrieval nehmen.

**Comment by Alex-J-W** [comment]
Dann wuerde ich mir gerne das Thema LangChain schnappen wenn es noch offen ist :)

**Comment by TimSchober** [comment]
Ich würde gerne das Thema "Open Source LLMs" nehmen.

**Comment by mayah1010** [comment]
Ich würde gern das Thema "Data Storytelling" übernehmen. Vielen Dank.

**Comment by pkeilbach** [comment]
> Ich würde gerne das Thema "Tensorflow for NLP" machen

As discussed @tiffanyblum I removed you from this topic. So this would be available again!

**Comment by LilianCharlotte** [comment]
Ich würde gerne "Thinking LLMs" präsentieren :).

**Comment by pkeilbach** [comment]
moved the topics for the current semester to #202 

moved the topic pool to #203

**Comment by julss97** [comment]
Ich hatte das Paper "From Single to Multi: How LLMs Hallucinate in Multi-Document Summarization" :)
